name: test22
favicon: null
layout_spectrum: 0.8148784989025444
typography_spectrum: 0.2808016196358949
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9082088707946241
  lightness: 0.9795877123251557
  saturation: 0.1446959760505706
  rhythmicContrast: 0.9191053071990609
purpose: []
